### ISSUE TITLE
Title?

### ISSUE THREAD

**Issue by Sekonda** [akiyamaSM/messager#11]
Hey,

Looking through the repo I see in the migration there is a [title column](https://github.com/akiyamaSM/messager/blob/master/src/migrations/2017_01_02_201510_create_messages_table.php#L20). 

What's this used for? I haven't seen it used anywhere.

**Comment by akiyamaSM** [comment]
Actually, its what I'll be adding for the next commit

**Comment by Sekonda** [comment]
Ah. I was tweaking the tests to try and get Travis running on the repo and they were failing because of it being empty. 

Do you want me to make it nullable  in my repo?

**Comment by akiyamaSM** [comment]
Sure, to be honest its my first package ever, so I'll need help untill I get used to it :D

**Comment by Sekonda** [comment]
No problem
