### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HDVinnie** [akiyamaSM/messager#21]
Does this package have a option like the Mail option in LARAVEL? So like a premade PM option?

`Mail::to($topicCreator->email)->send(new NewReply($user, $topic));`

**Comment by akiyamaSM** [comment]
Could you be more explcite? if you mean to send a 'real' mail I say no. Otherwise, I can make it the way you specified.

**Comment by HDVinnie** [comment]
So pretty much the above mail code sends a email to the forums topic creator and notifies them that a user have made a reply to there topic. 

I would rather not do emails. I would rather do it via a pm. I have a default user account named system that's user ID 0 could be used as the sender. 

I hope you understand what I want to accomplish

**Comment by akiyamaSM** [comment]
If I understand its kind of a Notification? for example if an event happened, send a PM to the concerned user

**Comment by HDVinnie** [comment]
Correct. So if I am the topic creator of a  thread for example. And there is a new reply to my topic I the topic creator would get APM sent to me saying that such and such user has replied to your topic called blah

**Comment by akiyamaSM** [comment]
I see its kinda good thing, But I really don't know if its a part of the package itself, it seems to me as a use case of the package itself.
I mean you can implement it based on it.
